### PR TITLE
add likes, closes #2

### LINKED ISSUE #2: feature: implement favorites on each post
Implementing favorites where the posts liked by the author gets commited to the author's source chain

### PR DESCRIPTION
**Pull request by science-girl**
As a user, I would like to mark posts I like with a red heart icon and later be able to click on a previously favourited item (filled red heart) and have it unfavourited (red heart outline).

### CODE REVIEW

**Review by bboyatwork — APPROVED** [review]
Looks good to me. The likes work and are persistent! The <3's are cute too 👍 I did notice exposed hash in hcdev web - dunno why that might be happening, or if it would show up live? [Screenshot](https://www.dropbox.com/s/mbvu49rmj1m1kmv/Screenshot%202018-06-12%2011.08.37.png?dl=0)

**Comment by science-girl** [comment]
@bboyatwork thanks! I thought I had deleted that...I had the hashes printed so I could make sure the right ones were being stored.  I can't seem them in my branch.  Maybe someone else can confirm?

**Comment by Connoropolous** [comment]
reviewing now... sorry it took me a while

**Comment by Connoropolous** [comment]
I'm not seeing the list of meows again when I refresh... but it looks like that's an issue on develop branch too :s

**Comment by Connoropolous** [comment]
I'm not seeing the list of Meows after I refresh... but it looks like thats an issue on the develop branch too :s

**Comment by science-girl** [comment]
@Connoropolous I can't remember if the meows previously persisted on refresh or not.  Looks like the refresh wipes out the redux store.  Should we use redux-persist or redux-storage? Or is there another possibility?

**Comment by Connoropolous** [comment]
I'm sure they're there. They're just not being fetched when the page loads.
The action already exists it just needs to be dispatched when the component
mounts. That should be done as a bug fix branch from the main develop
branch and a separate pr

**Comment by science-girl** [comment]
@Connoropolous created a new issue on the waffle board for it. https://waffle.io/holochain/org/cards/5b217e1643ca99001b96cdc7

**Comment by Connoropolous** [comment]
@science-girl so in theory, would this PR include showing on existing meows whether you liked them or not?

**Comment by science-girl** [comment]
Yes, this would be how a user would favourite tweets.  There is another PR for clicking on a link to show all the tweets you have favourited.

**Comment by zippy** [comment]
Hey @Connoropolous @science-girl, I loaded this up, did a `npm run build` and I'm getting a weird result.  In the UI I can add posts, and even click on the heart, but when I reload the UI, none of the posts appear.  It's as if they aren't getting stored correctly to the chain.

I'd love to get this ticket completed and merged as part of this sprint.  Can y'all tell me if I'm doing something wrong?

**Comment by zippy** [comment]
I see that this is not a problem with this branch but is a bug in the develop branch.  I've added #103 to address this.

**Review by zippy — APPROVED** [review]
This looks good.

**Pull request merged**
